### ISSUE TITLE
Errors while executing browserify-fs

### ISSUE THREAD

**Issue by srinivasthanneeru** [mafintosh/browserify-fs#8]
I'm seeing below error while accessing  - https://tonicdev.com/npm/browserify-fs on FF/Chrome on windows 7

ReferenceError: self is not defined
message: "self is not defined"
stack (getter): function()
stack (setter): function()
ReferenceError Prototype

...

While executing it on command line:
D:\>node test-bfs.js
D:\node_modules\browserify-fs\node_modules\level-js\node_modules\idb-wrapper\idb
store.js:129
        var env = typeof window == 'object' ? window : self;
                                                       ^

ReferenceError: self is not defined
    at new IDBStore (D:\node_modules\browserify-fs\node_modules\level-js\node_mo
dules\idb-wrapper\idbstore.js:129:56)
    at Level._open (D:\node_modules\browserify-fs\node_modules\level-js\index.js
:37:14)
    at Level.AbstractLevelDOWN.open (D:\node_modules\browserify-fs\node_modules\
level-js\node_modules\abstract-leveldown\abstract-leveldown.js:28:17)
    at LevelUP.open (D:\node_modules\browserify-fs\node_modules\levelup\lib\leve
lup.js:112:6)
    at new LevelUP (D:\node_modules\browserify-fs\node_modules\levelup\lib\level
up.js:82:8)
    at LevelUP (D:\node_modules\browserify-fs\node_modules\levelup\lib\levelup.j
s:44:12)
    at Object.<anonymous> (D:\node_modules\browserify-fs\index.js:5:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by gaurav517** [comment]
Did you find the resolution? I am getting the same error. Thanks.

**Comment by noveens** [comment]
same error :disappointed:

**Comment by GoMino** [comment]
Same problem here, is this library working ?

**Comment by art33nf** [comment]
Still getting this error

**Comment by HeidiHe** [comment]
same error +1

**Comment by jaxrein** [comment]
Have any of you solved this problem yet? I am seeing the same issue.
